bin/chore
lib/chore/cli.rb

This is a regression introduced by https://github.com/Tapjoy/chore/issues/5.  Invoking `Bundler.require` within a Rails app *prior* to actually loading the rails libraries causes issues.  In particular:
* There are some gems that simply assume that Rails has been loaded (rather than require dependencies)
* More importantly, Railtie files typically only get loaded by gems when they detect that Rails is available (via something like `defined?(Rails)`).
By requiring all gems ahead of time, we break the above two assumptions since there's no guarantee on when Rails actually gets loaded.  We could explicitly define the `require` option for every gem, but that's going to be full of headaches.
Instead, this makes that behavior part of Chore's bootup process.  The primary reason for having this …

Only explicitly use Bundler.require when in non-rails environments

---

lib/chore/hooks.rb

hi @Tapjoy/eng-group-services 
cc @StabbyCutyou 
This improves performance significantly (when we're not waiting on network I/O).
This does involve a slight change of behavior: hook methods defined dynamically after jobs begin processing will no longer be called. I think this is reasonable.

Memoize #methods in hook processing

---

lib/chore/strategies/worker/single_worker_strategy.rb

@Tapjoy/eng-group-services 
cc @StabbyCutyou 
We got another bad job file—and no more work was being processed, without error. This addresses that issue.

If the single worker raises an exception, ensure that it is released

---

lib/chore/strategies/worker/single_worker_strategy.rb
spec/chore/strategies/worker/single_worker_strategy_spec.rb

This is a fix for the issue where having multiple consumer threads in conjunction with a single worker strategy can cause work to be left by the side because we don't have any locking around the worker.  This effectively imitates what's being done in the forked worker strategy.
I've decided to not do any refactoring around how some of the logic here is similar to the forked worker strategy.  I think there's a larger thought here around replacing the single worker strategy with a threaded worker strategy -- and getting us to a place where that shares much of the same code as the forked worker strategy.  That's a problem for another day, though.
In the meantime this should at least resolve this particular failure with multiple consumer threads.
/to @StabbyCutyou 
/fyi …

Allow single worker strategy to be used in conjunction with multiple consumer threads

---

README.md
lib/chore/manager.rb

This adds a `before_start` hook that mirrors the `before_shutdown` hook.  It will run callbacks prior to starting the fetcher / worker strategy (which are responsible for consuming and processing jobs).  This is particularly useful for integrations like NewRelic where we can have a single hook that works regardless of the worker strategy in use.  Currently, NewRelic integrations must hook into the `before_first_fork` hook which doesn't work if you're not using a forked strategy.
/to @StabbyCutyou @theo-lanman 
/cc @Tapjoy/eng-group-services

Add before_start hook for running callbacks prior to starting consuming / processing

---

lib/chore/worker.rb
spec/chore/strategies/worker/forked_worker_strategy_spec.rb
spec/chore/worker_spec.rb

We should be calling the `#reject` API in the consumer when a job fails.  As per the documentation, `#reject` "should put a message back on a queue to be processed again later".  When a job fails, this is exactly what we want to happen.  Now, in the SQS case this is a no-op because there's no concept for that type of functionality -- you just wait a little while and the job will be back in the queue.
However, in the filesystem case, you must explicitly put the job back into the queue.  Without this change, any job that raises an exception will be stuck in "inprogress" until chore is restarted.  With this change in place, the job will be moved back to "new" and ready to be re-processed.  That does mean that jobs will get *immediately* re-processes, but I think that's better than being …

Reject failed jobs in the consumer

---

lib/chore/queues/filesystem/consumer.rb
lib/chore/queues/filesystem/publisher.rb

Some proposals to make the way we publisher to / consumer from the filesystem queue to be consistent with other places in chore:
1. Encode jobs with `encode_job` rather than `to_json`
2. Don't swallow errors when writing to the job file
3. Encode the job before creating a job file so as to avoid the possibility of empty job files on encoding failures
4. Use `rm -f` when deleting job files
This should make it more consistent with the general way we handling jobs in sqs (we don't swallow errors, we use `encode_job`, etc.)
/to @StabbyCutyou @theo-lanman @gregorysabatino

Improvements to filesystem queue handling

---

README.md
lib/chore.rb
lib/chore/strategies/consumer/batcher.rb
lib/chore/strategies/consumer/threaded_consumer_strategy.rb
lib/chore/unit_of_work.rb
spec/chore/strategies/consumer/batcher_spec.rb
spec/chore/strategies/consumer/threaded_consumer_strategy_spec.rb

This makes two changes:
1. The batch timeouts are now configurable instead of being hard-coded to 20s
2. We now run `execute` when the oldest message in the batcher has exceeded the timeout.
To provide a little context, the current behavior of the timeout is that it is based on the newest message in the batcher.  Consider the scenario where batch size = 10 and timeout = 1m.  If a message came in every 30s, then the batch wouldn't be processed until 5m has passed (because the batch size will then be 10).
I will also be looking for feedback / guidance on whether this should be a minor or major rev change.
/to @gregorysabatino @theo-lanman @StabbyCutyou

Change batch timeouts to be both configurable and based on the time oldest message

---

Gemfile
chore-core.gemspec
lib/chore.rb
lib/chore/cli.rb
lib/chore/consumer.rb
lib/chore/fetcher.rb
lib/chore/manager.rb
lib/chore/queues/sqs/consumer.rb
lib/chore/strategies/consumer/threaded_consumer_strategy.rb
lib/chore/strategies/consumer/throttled_consumer_strategy.rb
lib/chore/strategies/worker/forked_worker_strategy.rb
lib/chore/strategies/worker/helpers/ipc.rb
lib/chore/strategies/worker/helpers/preforked_worker.rb
lib/chore/strategies/worker/helpers/work_distributor.rb
lib/chore/strategies/worker/helpers/worker_info.rb
lib/chore/strategies/worker/helpers/worker_killer.rb
lib/chore/strategies/worker/helpers/worker_manager.rb
lib/chore/strategies/worker/preforked_worker_strategy.rb
lib/chore/util.rb
lib/chore/worker.rb
scripts/monitoring
spec/chore/queues/sqs/consumer_spec.rb
spec/chore/strategies/consumer/throttled_consumer_strategy_spec.rb
spec/chore/strategies/worker/helpers/ipc_spec.rb
spec/chore/strategies/worker/helpers/preforked_worker_spec.rb
spec/chore/strategies/worker/helpers/work_distributor_spec.rb
spec/chore/strategies/worker/helpers/worker_info_spec.rb
spec/chore/strategies/worker/helpers/worker_killer_spec.rb
spec/chore/strategies/worker/helpers/worker_manager_spec.rb
spec/chore/strategies/worker/preforked_worker_strategy_spec.rb

Objective
==
The main objective of the changes in this PR is to reduce job latencies on chore. We define latency on chore, as the time duration from when the message is consumed from a source, to when it is completed by a worker. The metric that we use to measure the latency is the average job latency per second. 
We aim to meet this objective with the introduction of these two strategies: 
- Pre-Forked worker strategy
- Throttled consumer strategy
Pre-Forked worker strategy: 
--
The goals of the pre-forked worker strategy are:
- Manage the lifecycle of a group of workers. 
- Manage job assignments to workers to minimize latency
Throttled consumer:
--
The goals of the throttled consumer strategy are:
- Minimize the jobs in the chore which are in-flight but not being worked on. 
- Always …

Preforked worker and throttled consumer strategies

---

lib/chore/strategies/worker/helpers/work_distributor.rb

@Tapjoy/tools @riteshnoronha @goose42 @Ceraunograph 
When trying to debug why some clicks where not being processed in Otto, I noticed that the WorkDistributor was swallowing exceptions and not providing any logging. This made debugging very difficult. Let's add some exception info.

add exception logging to help debugging

---

lib/chore/hooks.rb

This memoizes the candidate lookup for hooks so that we only do the search once per class.  Without this, there's a pretty significant amount of overhead when processing very small, very fast jobs at a large scale.
/to @Tapjoy/dmmeas

Memoize hook lookups to reduce performance impact when processing large numbers of jobs

---

lib/chore.rb
lib/chore/manager.rb
lib/chore/strategies/worker/forked_worker_strategy.rb
lib/chore/strategies/worker/helpers/preforked_worker.rb

We have some scenarios where we run multiple applications deployed onto the same servers each with their own master chore process.  Currently it's not possible to easily differentiate between these chore processes since they're all named the same.  This configuration would give applications the power to control the procline so that we can have different proclines and more easily monitor the processes.
/to @gregorysabatino @dankleiman @geoffreyclark

Allow the master / worker proclines to be configured by the app

---

lib/chore.rb
lib/chore/cli.rb
lib/chore/queues/filesystem/consumer.rb
lib/chore/queues/filesystem/filesystem_queue.rb
lib/chore/queues/sqs/consumer.rb
spec/chore/cli_spec.rb
spec/chore/queues/filesystem/filesystem_consumer_spec.rb

This makes a variety of performance / memory improvements to the filesystem consumer.  These are particularly effective when working with large backlogs.  This PR is best reviewed commit-by-commit.  Each change stands on its own, but I've bundled them into a single PR for the purpose of full context and how they're related.
Note that the reason I'm making these changes instead of investing time into the Go sidecar / FS queue is because there are only a few things we need to do to get our existing Ruby sidecar / FS queue behaving well enough to stand on its own.  Investing time into a Go implementation is a much larger chunk of work.
The following changes were made:
1. Only sleep between lookups in the filesystem consumer if files aren't found
Currently we sleep for 5s every time we we …

Various filesystem consumer improvements

---

lib/chore/consumer.rb
lib/chore/fetcher.rb
lib/chore/queues/filesystem/consumer.rb
spec/chore/consumer_spec.rb
spec/chore/fetcher_spec.rb
spec/chore/queues/filesystem/filesystem_consumer_spec.rb

In order to give us more flexibility in how we configure and deploy chore as a filesystem sidecar queue, this adds support for being able to run multiple chore masters or multiple forked workers.  Currently this is supported for external services like SQS; however, we don't have graceful support for it in the filesystem.
Similar to https://github.com/Tapjoy/chore/pull/43, this gets us a lot more flexibility in deployment configuration without investing time into a Go-based filesystem queue sidecar.
Currently the filesystem queue already supports multiple consumers across different processes.  However, the problem we still need to solve is what happens to in-progress jobs when a forked worker or master process dies.  The current implementation assumes only 1 master is ever running at a …

Support multiple chore processes consuming from the filesystem queue

---

lib/chore/queues/filesystem/consumer.rb
spec/chore/queues/filesystem/filesystem_consumer_spec.rb

When a queue has a large backlog, `Dir.glob` performs much more poorly than `Dir.foreach`.  I had originally switched to `glob` to simplify the code, but the performance regression is way more than its worth.  See below for a directory with 200k jobs:
```
2.3.0 :015 > Benchmark.measure { index = 0; Dir.glob('/mnt/chore_fs_queue/development_web_requests/new/*.job') {|f| index += 1; break if index >= 1000 } }
=> #<Benchmark::Tms:0x0000000214cb50 @label="", @real=0.5653504389993032, @cstime=0.0, @cutime=0.0, @stime=0.2999999999999998, @utime=0.26000000000000023, @total=0.56> 
2.3.0 :016 > Benchmark.measure { index = 0; Dir.foreach('/mnt/chore_fs_queue/development_web_requests/new/') {|f| index += 1; break if index >= 1000 } }
=> #<Benchmark::Tms:0x000000031ef318 @label="", …
```

Use Dir.foreach instead of Dir.glob to fix a performance regression

---

CHANGELOG.md
lib/chore/queues/filesystem/publisher.rb
lib/chore/version.rb

This makes a few fixes to how we publish files to the filesystem from chore:
1. When the filesystem publisher chooses a filename, it's possible that it conflicts with another file that already exists if the file gets created within a short enough timeframe in the same process.  When this happens, the file will be left in a permanently locked state until the Ruby process exits since we don't explicitly unlock the file in that case.
2. The file mutex isn't used because we only publish one file at a time in a single process (not multi-threaded) and we already have handling for conflicting files.
3. By using "w" as the file flag, Ruby documents that this can truncate existing files.  To avoid that, I've switched it to "a" which will either create or append files.  In the append case, we'll …

Fix filesystem publisher potentially leaving files locked until the Ruby process exits

---

lib/chore/consumer.rb
lib/chore/job.rb
lib/chore/queues/sqs/consumer.rb
lib/chore/version.rb
lib/chore/worker.rb
spec/chore/duplicate_detector_spec.rb
spec/chore/strategies/worker/forked_worker_strategy_spec.rb
spec/chore/worker_spec.rb

The goal of this PR is to allow chore jobs to define a custom lambda to be called before `perform`, the results of which we would use as a key to dedupe the job runs. We currently do part of this today for sqs message ids (sqs is "at-least once") in `sqs/consumer.rb`. Part of this PR refactors the code so that we are either doing one dedupe: using the custom job-defined function, or falling back to using the message id. 
A random sided-benefit of this PR is that by moving the deduping code from the `sqs/consumer` class to the `worker`, we actually _gain_ the ability to dedupe on filesystem queues which wasn't previously possible before.
One thing to keep in mind when reviewing this code is that the same chore triggers should be called as they were previously on duplicate messages. The …

[DMMEAS-1646] adds chore queue option to dedupe on arbitrary value per job

---

lib/chore/queues/sqs/consumer.rb
lib/chore/version.rb

If we take a look at the `visibility_timeout` method on `queue`, we can see it calls `get_queue_attributes` https://github.com/aws/aws-sdk-ruby/blob/aws-sdk-v1/lib/aws/sqs/queue.rb#L783 every time, which calls out to the API (https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/SQS/Client.html#get_queue_attributes-instance_method). We only want to do this one time per consumer, not message.

[no-jira] cache the queue visibility timeout rather than access the api twice

---

lib/chore/version.rb
lib/chore/worker.rb

This allows us to conditionally perform the secondary-deduping in chore on the dedupe-lambda results. It simply checks the results for either `nil` or an empty string, and if so, skips the deduping on the lambda.
To test this, I replaced the `UpdateLifetimeSpend` job on a tapinabox with a job that randomly returns either `nil` or a valid id for the dedupe-lambda for the purposes of testing (I really just need a pre-configured sqs queue):
```
class UpdateLifetimeSpendJob
include Chore::Job
queue_options name: 'v1_UpdateLifetimeSpend', :dedupe_lambda => lambda {|id|
if rand > 0.5
Rails.logger.info("UpdateLifetimeSpendJob: returned nil, not deduping")
return nil
else
return id
end
}
def perform(id)
end
end
```
In the cases where the lambda returns `nil`, we expect the job to run, which it …

[no-jira] add ability for dedupe_lambdas to return nil to skip checking

---

CHANGELOG.md
lib/chore/cli.rb
lib/chore/version.rb
spec/chore/cli_spec.rb

The prefixing should be handled entirely by the consuming application, rather than Chore appending to it at the last second.
We started running into this when we (I) unified the queue prefixing logic between our application's `Chorefile` (consume) and the `Chore.config` (publish) we use in our Chore initializer. This change did not affect our production applications, because we don't use `--queue-prefix` at all in our production environments.
- We'll use 4.1.0 instead.
- No, we don't :)
---
Given the long history of this behavior, I am also open to _not_ doing this and instead heavily commenting the reasons why our prefixing logic differs between the Chorefile and the initializers in our applications.

Remove appended underscore from CLI `--queue-prefix`

---

CHANGELOG.md
README.md
lib/chore/job.rb
lib/chore/version.rb
lib/chore/worker.rb
spec/chore/job_spec.rb
spec/chore/worker_spec.rb

add around_publish hook for workers
- wrap `@chore_publisher.publish(self.class.prefixed_queue_name,publish_job_hash)`
- allows for updating the `job_hash` (actual hash payload pushed to queue)
add around_perform hook for jobs
- wrap `perform_job(klass, message)`
https://tapjoy.atlassian.net/browse/DFUN-53

Add around_publish and around_perform

---

.buginfo
CODEOWNERS

https://jira.unity3d.com/browse/OSEC-2808
In order to help us integrate better with various Unity tools, we are creating `CODEOWNERS` and `.buginfo` files in all of our repositories.  You can learn more about these in the Jira ticket.
The assignments in this PR are based on assessments from this spreadsheet:
* https://docs.google.com/spreadsheets/d/1ufKQiMK4NZM-6LNfLhO-93MBDdAJXh1S6oQppiRcHkw/edit#gid=705595020
Relevant links:
* [Github team](https://github.com/orgs/Tapjoy/teams/eng-group-platform)
* [Jira project](https://jira.unity3d.com/browse/NPE)
What we're primarily looking for out of this PR review:
* Ensure that the proper team and Jira project are being assigned
* Ensure there are no syntax issues called out by github in the `CODEOWNERS` file

SEC-2808: Add CODEOWNERS and .buginfo files

---

lib/chore/consumer.rb
lib/chore/duplicate_detector.rb
lib/chore/queues/filesystem/consumer.rb
lib/chore/queues/sqs/consumer.rb
lib/chore/strategies/consumer/single_consumer_strategy.rb
lib/chore/strategies/consumer/threaded_consumer_strategy.rb
lib/chore/strategies/consumer/throttled_consumer_strategy.rb
lib/chore/unit_of_work.rb
lib/chore/version.rb
lib/chore/worker.rb
spec/chore/duplicate_detector_spec.rb
spec/chore/queues/filesystem/filesystem_consumer_spec.rb
spec/chore/queues/sqs/consumer_spec.rb
spec/chore/strategies/consumer/single_consumer_strategy_spec.rb
spec/chore/strategies/consumer/threaded_consumer_strategy_spec.rb

[REWARDS-417](https://jira.unity3d.com/projects/REWARDS/boards/926) investigation led me to Chore, the job scheduler for SQS in TJS.
After some discussion and digging, it looks like the deduplication logic is removing messages from the queue before the retention window expires. This race condition happens when we 1. consume a message and 2. add the message to the dedupe  cache with a TTL based on the SQS visibility timeout. Between 1 and 2, some time passes which can be less than a second up to 2 seconds. ([link to data](https://docs.google.com/spreadsheets/d/1vZObLyYy3uojKhDsyBqGz82g2hDysILE2RWRWMfjI_0/edit?pli=1#gid=237898670)) Sometimes the message in the dedupe cache does not expire before we see another request for the same Reward ID. This causes the message to be removed from the …

[REWARDS-417] Update Dedupe Queue TTL
